# Generated by Django 2.2 on 2019-05-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('Index', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('Index', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('Index', models.AutoField(primary_key=True, serialize=False)),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attribute')),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Object')),
            ],
        ),
    ]
